#!/bin/bash
#SBATCH --job-name=llm-emph-grid
#SBATCH --time=1-2:00:00
#SBATCH --nodes=1
#SBATCH --mem=100G
#SBATCH --gpus=3
#SBATCH --cpus-per-task=8
#SBATCH --output=logs/rec/%x-%j.out
#SBATCH --error=logs/rec/%x-%j.err

source ~/miniconda3/etc/profile.d/conda.sh
conda activate llm_emph

# change actor_param and model-id as needed

stdbuf -oL -eL python -u -m rec.test_emphasis \
  --actor_param ckpt_emph/GRPO/qwen/0.5/actor_emph_step3000.pt \
  --model-id Qwen/Qwen2.5-14B-Instruct \
  --llm-inputs data/lm_inputs.jsonl \
  --labels data/test_split.jsonl \
  --adj data/covis_adj.jsonl \
  --meta data/compact_meta.jsonl \
  --actor qwen \
  --candidates 40 --topk 10 \
  --per-bin 250 \
  --start-tok "<important>" --end-tok "</important>"