#!/bin/bash
#SBATCH --job-name=llm-emph-grid
#SBATCH --time=1-2:00:00
#SBATCH --nodes=1
#SBATCH --mem=100G
#SBATCH --gpus=6
#SBATCH --cpus-per-task=8
#SBATCH --output=logs/rec/%x-%j.out
#SBATCH --error=logs/rec/%x-%j.err

source ~/miniconda3/etc/profile.d/conda.sh
conda activate llm_emph

# change actor_model and model-id as needed
Model_ID="Qwen/Qwen2.5-14B-Instruct"
Actor_Model_ID="Qwen/Qwen2.5-1.5B-Instruct"
CKPT=0 


SAVE_DIR="ckpt_emph/beauty/${Model_ID//\//_}/GRPO/actor-${Actor_Model_ID//\//_}"

stdbuf -oL -eL python -u -m rec.train_emphasis \
  --llm-inputs data/lm_inputs.jsonl \
  --labels data/test_split.jsonl \
  --adj data/covis_adj.jsonl \
  --meta data/compact_meta.jsonl \
  --topk 10 \
  --candidates 40 \
  --algorithm GRPO \
  --train-steps 10000 \
  --actor lm \
  --ckpt $CKPT \
  --model-id $Model_ID \
  --actor-model-id $Actor_Model_ID \
  --save_dir $SAVE_DIR \